name: Docker Image CI

on:
  push:
    tags:        
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mmurilo/pia-openvpn:${{ github.ref }}
    - name: Login Docker hub
      run: echo ${{ secrets.DOCKER_HUB_PASS }} | docker login --username ${{ secrets.DOCKER_HUB_USER }} --password-stdin
    - name: Push
      run: docker push mmurilo/pia-openvpn:${{ github.ref }}
